export const CONTINUE_CERTIFICATIONS = [
  {
    id: 1,
    title: 'AWS Certified Solutions Architect',
    image: 'https://images.unsplash.com/photo-1517694712202-14dd9538aa97?w=400&h=250&fit=crop ',
    instructor: {
      name: 'Lira',
      avatar: 'https://i.pravatar.cc/150?img=1 ',
    },
    status: 'Live',
    progress: 3,
    totalLessons: 7,
  },
  {
    id: 2,
    title: 'AWS Certified Solutions Architect',
    image: 'https://images.unsplash.com/photo-1517694712202-14dd9538aa97?w=400&h=250&fit=crop ',
    instructor: {
      name: 'John',
      avatar: 'https://i.pravatar.cc/150?img=2 ',
    },
    status: 'Live',
    progress: 5,
    totalLessons: 7,
  },
  {
    id: 3,
    title: 'AWS Certified Solutions Architect',
    image: 'https://images.unsplash.com/photo-1517694712202-14dd9538aa97?w=400&h=250&fit=crop ',
    instructor: {
      name: 'Sara',
      avatar: 'https://i.pravatar.cc/150?img=3 ',
    },
    status: 'Live',
    progress: 1,
    totalLessons: 7,
  },
  {
    id: 4,
    title: 'AWS Certified Solutions Architect',
    image: 'https://images.unsplash.com/photo-1517694712202-14dd9538aa97?w=400&h=250&fit=crop ',
    instructor: {
      name: 'Mike',
      avatar: 'https://i.pravatar.cc/150?img=4 ',
    },
    status: 'Live',
    progress: 4,
    totalLessons: 7,
  },
  {
    id: 5,
    title: 'AWS Certified Solutions Architect',
    image: 'https://images.unsplash.com/photo-1517694712202-14dd9538aa97?w=400&h=250&fit=crop ',
    instructor: {
      name: 'Emma',
      avatar: 'https://i.pravatar.cc/150?img=5 ',
    },
    status: 'Live',
    progress: 2,
    totalLessons: 7,
  },
  {
    id: 6,
    title: 'AWS Certified Solutions Architect',
    image: 'https://images.unsplash.com/photo-1517694712202-14dd9538aa97?w=400&h=250&fit=crop ',
    instructor: {
      name: 'David',
      avatar: 'https://i.pravatar.cc/150?img=6 ',
    },
    status: 'Live',
    progress: 6,
    totalLessons: 7,
  },
]

export const MY_CERTIFICATES = [
  {
    id: 1,
    name: 'Cloud Architect',
    title: 'AWS Certified Solutions Architect',
    holderName: 'Enter Name Here',
    issuer: 'Amazon Web Services',
    issueDate: 'Jul 2023',
    expiryDate: 'Present',
    description: 'Lorem ipsum dolor sit amet of cloud computing and architecture fundamentals with AWS certification.',
  },
  {
    id: 2,
    name: 'DevOps Engineer',
    title: 'AWS Certified DevOps Engineer',
    holderName: 'Enter Name Here',
    issuer: 'Amazon Web Services',
    issueDate: 'Aug 2023',
    expiryDate: 'Present',
    description: 'Lorem ipsum dolor sit amet of deployment and operations on AWS infrastructure with hands-on experience.',
  },
  {
    id: 3,
    name: 'Data Engineer',
    title: 'AWS Certified Data Engineer',
    holderName: 'Enter Name Here',
    issuer: 'Amazon Web Services',
    issueDate: 'Sep 2023',
    expiryDate: 'Present',
    description: 'Lorem ipsum dolor sit amet of data pipeline development and analytics with AWS specialized tools.',
  },
  {
    id: 4,
    name: 'Cloud Architect',
    title: 'AWS Certified Solutions Architect',
    holderName: 'Enter Name Here',
    issuer: 'Amazon Web Services',
    issueDate: 'Jul 2022',
    expiryDate: 'Present',
    description: 'Lorem ipsum dolor sit amet of cloud architecture design patterns and best practices with AWS.',
  },
  {
    id: 5,
    name: 'Security Engineer',
    title: 'AWS Certified Security Specialist',
    holderName: 'Enter Name Here',
    issuer: 'Amazon Web Services',
    issueDate: 'Jun 2023',
    expiryDate: 'Present',
    description: 'Lorem ipsum dolor sit amet of security principles and implementation on the AWS platform.',
  },
  {
    id: 6,
    name: 'Solutions Architect',
    title: 'AWS Certified Solutions Architect',
    holderName: 'Enter Name Here',
    issuer: 'Amazon Web Services',
    issueDate: 'May 2023',
    expiryDate: 'Present',
    description: 'Lorem ipsum dolor sit amet of designing distributed systems and scalable architectures on AWS.',
  },
]