export const DUMMY_COURSES = [
  {
    id: 1,
    title: "HTML & CSS Mastery 2025 - Build Modern Websites",
    description:
      "Master modern HTML5 and CSS3 from scratch. Build responsive, accessible websites with Flexbox, Grid, and animations.",
    category: "Programming",
    duration: "3 Months",
    skill: "HTML/CSS",
    department: "Engineering",
    role: "Frontend Developer",
    instructor: { name: "Lira Johnson", avatar: "https://i.pravatar.cc/150?img=1" },
    price: 0,
    image: "https://upload.wikimedia.org/wikipedia/commons/e/e3/Udemy_logo.svg",
    platform: "Udemy",
    url: "https://www.udemy.com/course/html-css-mastery-2025/",
  },
  {
    id: 2,
    title: "AWS Cloud Practitioner Essentials",
    description:
      "Learn AWS fundamentals including EC2, S3, and RDS. Prepare for the AWS Certified Cloud Practitioner exam.",
    category: "Cloud",
    duration: "2 Months",
    skill: "AWS",
    department: "Engineering",
    role: "Cloud Architect",
    instructor: { name: "Sarah Chen", avatar: "https://i.pravatar.cc/150?img=5" },
    price: 0,
    image: "https://upload.wikimedia.org/wikipedia/commons/5/51/IBM_logo.svg",
    platform: "IBM SkillsBuild",
    url: "https://skillsbuild.org/",
  },
  {
    id: 3,
    title: "React.js Fundamentals - Complete Guide",
    description:
      "Master React hooks, components, and state management. Build modern single-page applications from scratch.",
    category: "Programming",
    duration: "4 Months",
    skill: "React",
    department: "Engineering",
    role: "Full Stack Developer",
    instructor: { name: "Mike Ross", avatar: "https://i.pravatar.cc/150?img=8" },
    price: 0,
    image: "https://upload.wikimedia.org/wikipedia/commons/e/e3/Udemy_logo.svg",
    platform: "Udemy",
    url: "https://www.udemy.com/",
  },
  {
    id: 4,
    title: "Azure Fundamentals AZ-900",
    description:
      "Microsoft Azure basics including cloud concepts, core services, security, privacy, compliance, and pricing.",
    category: "Cloud",
    duration: "3 Months",
    skill: "Azure",
    department: "IT",
    role: "Cloud Engineer",
    instructor: { name: "Emily Davis", avatar: "https://i.pravatar.cc/150?img=9" },
    price: 0,
    image: "https://upload.wikimedia.org/wikipedia/commons/4/44/Microsoft_logo.svg",
    platform: "Microsoft Learning",
    url: "https://learn.microsoft.com/training/",
  },
  {
    id: 5,
    title: "Leadership and Management Essentials",
    description:
      "Develop critical leadership skills, team management, and strategic thinking for modern business environments.",
    category: "Management",
    duration: "2 Months",
    skill: "Leadership",
    department: "Operations",
    role: "Manager",
    instructor: { name: "Robert Wilson", avatar: "https://i.pravatar.cc/150?img=11" },
    price: 0,
    image: "https://upload.wikimedia.org/wikipedia/commons/c/ca/LinkedIn_logo_initials.png",
    platform: "LinkedIn Learning",
    url: "https://www.linkedin.com/learning/",
  },
  {
    id: 6,
    title: "Python for Data Science",
    description:
      "Learn Python programming with focus on data analysis, Pandas, NumPy, and data visualization techniques.",
    category: "Data Science",
    duration: "3 Months",
    skill: "Python",
    department: "Analytics",
    role: "Data Scientist",
    instructor: { name: "Alex Turner", avatar: "https://i.pravatar.cc/150?img=12" },
    price: 0,
    image: "https://upload.wikimedia.org/wikipedia/commons/e/e3/Udemy_logo.svg",
    platform: "Udemy",
    url: "https://www.udemy.com/",
  },
  {
    id: 7,
    title: "Cybersecurity Fundamentals",
    description:
      "IBM's comprehensive cybersecurity course covering network security, threats, and protection strategies.",
    category: "Security",
    duration: "4 Months",
    skill: "Cybersecurity",
    department: "IT",
    role: "Security Analyst",
    instructor: { name: "Lisa Park", avatar: "https://i.pravatar.cc/150?img=15" },
    price: 0,
    image: "https://upload.wikimedia.org/wikipedia/commons/5/51/IBM_logo.svg",
    platform: "IBM SkillsBuild",
    url: "https://skillsbuild.org/",
  },
  {
    id: 8,
    title: "Power Platform Fundamentals",
    description:
      "Microsoft Power Apps, Power Automate, and Power BI basics for business process automation.",
    category: "Low-Code",
    duration: "2 Months",
    skill: "Power Platform",
    department: "Operations",
    role: "Business Analyst",
    instructor: { name: "David Kim", avatar: "https://i.pravatar.cc/150?img=3" },
    price: 0,
    image: "https://upload.wikimedia.org/wikipedia/commons/4/44/Microsoft_logo.svg",
    platform: "Microsoft Learning",
    url: "https://learn.microsoft.com/training/",
  },
];

export const PLATFORMS = [
  {
    name: "Microsoft Learning",
    href: "https://learn.microsoft.com/training/",
    logo: "https://upload.wikimedia.org/wikipedia/commons/4/44/Microsoft_logo.svg",
  },
  {
    name: "Udemy",
    href: "https://www.udemy.com/",
    logo: "https://upload.wikimedia.org/wikipedia/commons/e/e3/Udemy_logo.svg",
  },
  {
    name: "LinkedIn Learning",
    href: "https://www.linkedin.com/learning/",
    logo: "https://upload.wikimedia.org/wikipedia/commons/c/ca/LinkedIn_logo_initials.png",
  },
  {
    name: "IBM SkillsBuild",
    href: "https://skillsbuild.org/",
    logo: "https://upload.wikimedia.org/wikipedia/commons/5/51/IBM_logo.svg",
  },
];

export const ITEMS_PER_PAGE = 6;